# Generated by Django 3.0.5 on 2021-09-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='county',
            new_name='country',
        ),
    ]
