# Generated by Django 3.0.5 on 2021-08-22 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delivery'),
        ('shop', '0006_auto_20210810_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Delivery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 18, 31, 51, 457059), null=True),
        ),
    ]
