# Generated by Django 3.0.5 on 2021-09-15 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210822_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='providerId',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 22, 23, 57, 603260), null=True),
        ),
    ]
